version: "3.9"  

services:

  pimezon-photo-embedding:
    image: pimezon/embedding:cuda
    environment:
      - WORKERS=1
    ports:
      - 8080:5000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
          test: "curl --fail http://localhost:5000/healthcheck || exit 1"
          interval: 60s
          retries: 3
          start_period: 45s
          timeout: 5s
